---
title: "06 - Barebones Git and GitHub"
author: Jeffrey W. Hollister
layout: post_page
---

```{r setup, echo=FALSE, warning=FALSE, purl=FALSE, message=FALSE}
options(repos="http://cran.rstudio.com/")

#If libraries needed in post, load here.  include in code block later with 
#eval = FALSE.  Cleaner that way.
#if(!require("ggplot2")){
#  install.packages("ggplot2")
#}
#library("ggplot2")
```

Collaboration is essential to science, and requires understanding both the social side to collaboration as well as the logistical, nuts-and-bolts, technical side.  In spite of its importance, we get very little training in how to do this.  In this lesson we are going to start to focus on the technical side of collaboration.  Given the limited time we have, we are going to show you the bare bones of [GitHub](https://github.com) and the underlying version control technology, [Git](https://git-scm.com/).  

##Lesson Goals
- Understand Git and GitHub and how they work together
- Be able to use basic Git commands from the shell
- Be able to use RSutdio's Git interface

##Quick Links to Exercises and R code
- [Exercise 1](#exercise-1): Create a repository on GitHub
- [Exercise 2](#exercise-2): Set-up global configuration on local machine
- [Exercise 3](#exercise-3): Use Git from shell to push initial changes
- [Exercise 4](#exercise-4): Use RStudio with your GitHub repository

##Git and GitHub

Git and GitHub are two releated, but separate entities.  Git could exisit without GitHub, but GitHub probably couldn't.  

###What is Git?

Git is version control software, nothing more.  It was originally built to manage the development of the Linux Kernel.  Since then it has taken off and is, arguably, the most widely used software for managing versions of code (and really any text).  It is designed to work in a distributed fashion.  What this means, is that we can each have our version of the code (or text), then, if we want, combine those together into a centralized, master version.  Since it is distributed, it deals with multiple changes, from multiple people and it  provides mechanisms to combine those changes together.  In essence, think of it as "track-changes" on steroids.  We'll get into more details in a bit.

###What is GitHub?

GitHub is a website that facilitates sharing and colloborating on coding (and text) projects.  It serves as a cenralized location to store code, data, and files related to a project and also has a social component to it in that you can follow other users, star projects, etc.  It has grown tremendously in the last 5 years or so and houses some pretty big name projects (e.g. the Linux Kernel,jQuery) and, increasingly, is getting used more and more for hosting scientific projects.  It relies heavily on Git and much of the structure and functionality is an outgrowth of this reliance.

##Basics of Git

##Exercise 1

##Basics of Github

##Exercise 2

